### ISSUE TITLE
Capture escape sequences

### ISSUE THREAD

**Issue by dlvhdr** [mskelton/tmux-last#3]
I didn't test it with this plugin, but tmux's `capture-pane` command has a `-e` flag to also capture escape sequences.
This will allow us to also capture colored output etc.

From quick testing it seems to work:
```fish
set test (tmux capture-pane -e -p -J)
echo $test
```

**Comment by mskelton** [comment]
I added a new flag `@tmux-last-color` to make this work.  Off by default as it takes a little extra configuration for prompt patterns and such plus `PAGER` doesn't usually include flags to consume escape codes by default (I assume).

https://github.com/mskelton/dotfiles/commit/86c171e9
